### ISSUE TITLE
Mujoco App or UI "Save xml" button file location

### ISSUE THREAD

**Issue by Olimoyo** [deepmind/mujoco#110]
Hi, 

I am using the default macOS Mujoco App.
 
Is there a default location for where the XML files are stored when you press the "Save xml" button?
<img width="454" alt="Screen Shot 2022-01-13 at 3 47 55 PM" src="https://user-images.githubusercontent.com/14180933/149406927-04d6f037-fc30-4872-a971-2c3a90f2fcd7.png">

Thanks,
Oliver

**Comment by Olimoyo** [comment]
I figured it out, it was under:
`/Applications/MuJoCo.app/Contents/Resources`

**Comment by yuvaltassa** [comment]
Yes, this is indeed not great. Ideally, we would have a proper save dialog box.
If anyone wants to make a PR for this that would be appreciated.

**Comment by saran-t** [comment]
Ideally we'd open up a "Save as..." dialog box when you're saving a file. Might be a bit platform-dependent though, but as @yuvaltassa said since the simulate code is open source we'd welcome any pull request for this.

I'll reopen the issue in case anyone wants to fix it.

**Comment by saran-t** [comment]
A dialog box has been added [on macOS](https://github.com/deepmind/mujoco/blob/main/sample/macos_save.mm) so that the user can choose which directory they want the XML to be written into. 

We haven't added this for Windows or Linux yet. Doing this for Windows should be reasonably straightforward and not too dissimilar to what we did for macOS. Linux is a bit trickier since there isn't a "standard" API for this, and we'd prefer to not introduce a dependency just for a dialog box. If anyone has a good idea for this, please feel free to send us a PR.

**Comment by csingh27** [comment]
Where is it stored by default in ubuntu?

**Comment by rtnow** [comment]
> > Where is it stored by default in ubuntu?
> 
> In the directory where the simulate binary is run from.

what about windows？thanks for answer me
