### ISSUE TITLE
how to add points into "geom" object so that I can visualize the path along which a robot has moved?

### ISSUE THREAD

**Issue by Ramoflaple** [deepmind/mujoco#204]
in certain applications, we need to visualize the path along which a robot has moved. 
Is it possible for mujoco to provide points (or even better frames)  geometry type as a placeholder, so that we can dynamicly feed data (e.g. end effector‘s position/frame) into it  and then let mujoco draw these points/frames in the scene?

**Comment by yuvaltassa** [comment]
The easy way to do this is with sites, which are exactly that: frames. You can add a thousand invisible sites to your model and at runtime move them around and make them visible.

However, this will add some (small) overhead your physics computation. If you need to maximise speed, you probably want to draw objects directly into your mjvScene, as discussed in #132.

**Comment by Ramoflaple** [comment]
> The easy way to do this is with sites, which are exactly that: frames. You can add a thousand invisible sites to your model and at runtime move them around and make them visible.
> 
> However, this will add some (small) overhead your physics computation. If you need to maximise speed, you probably want to draw objects directly into your mjvScene, as discussed in #132.

thank you very much!

**Comment by Joaopmoliveira** [comment]
Hi,
I am trying to use your engine (great work btw) and we are simulating a robotic system being controled with a gaussian process (demonstration learning).
To help understand the data in real time we would like to render a mesh which corresponds to the variance of the GP over the scene before triggering the simulation.
The problem is that the mujoco context has a fixed preallocated number of buffers for skins so I can't figure out how to add this custom geometry with the tools you described above.
Any advice would be very appreciated!

**Comment by yuvaltassa** [comment]
Hi @Joaopmoliveira,

See comments [here](https://github.com/deepmind/mujoco/issues/132#issuecomment-1146886201).

**Comment by yuvaltassa** [comment]
There is a now a section in [this colab](https://github.com/deepmind/dm_control/blob/main/dm_control/mujoco/tutorial.ipynb) called "Adding arbitrary 3D geometry".
