### ISSUE TITLE
Is it possible to switch to Y-Up?

### ISSUE THREAD

**Issue by livinamuk** [deepmind/mujoco#207]
I'm experiencing a lot of oreintational headache switching between the two conventions and trying to render the scene correctly.

**Comment by erez-tom** [comment]
You could simply redefine "down" by changing the gravity vector.
However, I expect the problem you're experiencing is deeper: MuJoCo uses right-handed frames, while graphics engines often use left-handed frames.  We had to deal with this in the Unity plug-in, since Unity is left-handed.  We discuss it briefly [here](https://mujoco.readthedocs.io/en/latest/unity.html#design-principles): you need to keep track the frame of every vector, and [swizzle](https://en.wikipedia.org/wiki/Swizzling_(computer_graphics)) at every transition from one handedness to the other.  Our implementation lives [here](https://github.com/deepmind/mujoco/blob/main/unity/Runtime/Tools/MjEngineTool.cs#L112) (and elsewhere in that file).
