### ISSUE TITLE
Joint Offset Apperance in Hinge Joints 

### ISSUE THREAD

**Issue by anas-abulehia** [deepmind/mujoco#361]
**joint offset appearance**

Hi,

I'm a student and I'm trying to use MuJoCo for simulation and control of a mechanical system of 2 Degree of Freedom. 
The system is composed from 2 mechanical masses with 2 free rotational hinges. The first rotation is around x, the second rotation is around y. 
See the first figure when initial conditions were zeros. 
The second figure shows the system with non zeros initial conditions. 
The following video link demonstrates the system.  
https://www.youtube.com/watch?v=mrPFJA59Ykw

Why this offset appears ? how to remove it ?

Regards, 

Here is a model which explains my question:

<details>
  <summary>minimal XML</summary>

```XML
<mujoco>
	<worldbody>
        <light diffuse=".5 .5 .5" pos="0 0 3" dir="0 0 -1"/>
		<geom type="plane" size="6 6 0.1" rgba=".9 0 0 1"/>
		<body name ="mass 1"pos="0 0 2.5" euler="0  20  0">
			<geom type="cylinder" size="0.05 0.5" rgba="0 .9 0 1" mass="1"/>
			<joint name="pin" type="hinge" axis = "0 1 0" pos="0 0 0.5"/>
			<body name ="mass 2 " pos="0 0 -1" euler="40 0 0">
				<geom type="cylinder" size="0.05 0.5" rgba="0 0 .9 1" mass="1"/>
				<joint name="pin2" type="hinge" axis = "1 0 0" pos="0 0 0.5"/>
			</body>
		</body>
	</worldbody>
</mujoco>
```

</details>

Here is a screenshot / video, illustrating my question:
![Screenshot from 2022-06-25 22-52-35](https://user-images.githubusercontent.com/49106882/175790677-c07d30ac-eb47-44cd-9b16-a41bb206408c.png)
![Screenshot from 2022-06-25 22-16-20](https://user-images.githubusercontent.com/49106882/175790678-a17d3400-3081-4704-b120-7a72c03e39e0.png)

**Comment by yuvaltassa** [comment]
First of all to be clear, this is not a visualisation issue, your joint is being placed where you are asking to place it.

I think you are misunderstanding the position specifiers in the XML. They are always **in the parent frame**. Because you are rotating the body frames using `euler` your child body and joint are not where you expect them to be. I recommend to:

1. Visualise your _body frames_ in `simulate`, this will help you understand where you are placing things.
2. Experiment with the the `fromto` specifier for geoms.
