### ISSUE TITLE
How to make tendon have collision attribute?

### ISSUE THREAD

**Issue by takuyaliu** [deepmind/mujoco#511]
Hi,

I'm a student and I'm trying to use MuJoCo for simulating some ropes.

I used tendon to simulate the rope, like this:

![image](https://user-images.githubusercontent.com/96405341/193764370-805ce7c5-d584-4ed4-80f1-7a88cf4e1925.png)

But I found that the use of tendon in the simulation will directly pass through the model of the robot itself, like this:

![image](https://user-images.githubusercontent.com/96405341/193767567-5304160b-31ed-4717-8c95-58d36cc82095.png)

I tried to use geom to limit tendon's path, but not every rope can be restricted. Spatial can only pass through the cyclinder or sphere model specified by geom, and the attribute of spatial does not allow tendon to pass through two geoms without site in the middle, which is inconsistent with the reality.

Like this rope, it should have stretched the bottom toe in front of the robot leg:
![image](https://user-images.githubusercontent.com/96405341/193766177-69936495-7449-47d2-ad38-c8a312d306d4.png)

But in the actual simulation, it seems that because there is no collision attribute, tendon directly passes through the mesh model file of the robot leg (green line):
![image](https://user-images.githubusercontent.com/96405341/193766429-6b03d521-d637-41e1-8727-4a9e03cad5e3.png)

I would like to ask if you can assign the physical collision attribute to tendon, so that tendon can collide with other mesh files in the model, so as to achieve real collision and linkage effects.

Is it feasible to add collision attributes to tendon? Or should I use another method?

Look forward to receiving your reply. Thanks for reading, wish you all happy everyday : )

**Comment by yuvaltassa** [comment]
Tendons cannot collide, other than with wrapping geoms, sorry about that.
I recommend making a simplified model (perhaps starting with [this one](https://mujoco.readthedocs.io/en/latest/XMLreference.html#tendon-spatial)), and exploring how tendons interact with wrapping geoms. Note that even though the wrapping is **plotted** as a straight line inside the wrapping geom, the geometry is correct, i.e. the length of the tendon is computed as wrapping along the geom **surface**. 
I realise that there are quite a few limitations in what one can model, but these are all due to the requirement that the wrapping path be analytically computable and therefore very fast.

If you have any specific questions after this exploration, please attach a minimal loadable model that illustrates your question.
