### ISSUE TITLE
Simulating muscle/tendon mass

### ISSUE THREAD

**Issue by ericchen321** [deepmind/mujoco#543]
Hi, I'm trying to use MuJoCo to simulate a musculoskeletal arm model (like [the 2-link-6-muscle arm model](https://github.com/deepmind/mujoco/blob/main/model/tendon_arm/arm26.xml)). Specifically, I'd like to decouple muscle mass from bone mass (illustrated below).
![tendon_mass](https://user-images.githubusercontent.com/22675300/197304636-1a17e01f-4b2c-43ad-b5c0-6f9ad4c5e2b1.png)

But it seems like in MuJoCo muscles are actuators that do not have geometric or inertial properties, and we can't specify the mass of a tendon either.

**Would it be feasible to make some changes to how muscle/tendon is implemented so they can have mass?** The simplest approach I can think of is to make tendons massive objects, and specify their mass in lieu of muscle mass. I'm not planning to model the complex geometry of a real human muscle, so as long as I can make the mass uniformly distributed along the tendon it's good to me.

**Comment by yuvaltassa** [comment]
Can you explain why you want to do this?

In short the answer is no. Giving mass to tendons is not well defined, as that mass would need to be spread amongst the DoFs to which the tendon is coupled to in a length-dependent way. It is (in principle) possible to allow the addition of `armature` to tendons, which is a kind of inertia that would affect the tendon lengthening and shortening, but would be invisible otherwise (e.g. would not affect total body mass). This may or may not be what you want (see question above).

The way one would model proper muscle mass in MuJoCo is to introduce a new muscle body with its own degree of freedom. See discussion in #305.
