### ISSUE TITLE
Performance regression in mj_copyData (2.3.0 vs 2.1.0 )

### ISSUE THREAD

**Issue by ThoenigAdrian** [deepmind/mujoco#568]
Hi,

I recently migrated a mujoco project from mujoco version 2.1.0 to 2.3.0. I discovered that my application is running way slower. I ran a performance profiler to see why. 

![image](https://user-images.githubusercontent.com/16619270/200630900-5d4c70ce-e84d-46cb-8ddc-a0aece5baed4.png)

![image](https://user-images.githubusercontent.com/16619270/200631196-93374cce-e48e-4e91-9139-cc06ab9306e3.png)

Turns out mj_copyData is way slower than before. 
For those who are wondering about my motivations and why I'm doing this: I am copying the data, because i have 2 threads one in which i run the simulation and the main thread where i render/visualize.

Reproduce: I can provide a minimal working example if needed. However in this case I think it should be very easy to reproduce and compare. But if it isn't, I can provide something just let me know. 

- Include the following context:
  - Windows 10 x64
  - MuJoCo version 2.3.0 vs MuJoCo version 2.1.0

**Comment by yuvaltassa** [comment]
Thanks, we will look into this. 

In order to help us diagnose, could you please print `mjData.nstack` and `mjData.nbuffer` in both cases?


However, you should know that `mj_copyData` is **not** the recommended way to duplicate an `mjData`. This is mentioned [here](https://mujoco.readthedocs.io/en/latest/programming.html#state-and-control). As explained [here](https://mujoco.readthedocs.io/en/latest/computation.html#the-state), MuJoCo has a well-defined state. You shuld just be copying over the state. In your case, for visualisation purposes, it is enough to copy `qpos` and then `mj_fwdPosition`, or if you want to visualise forces then copy the entire [integration state](https://mujoco.readthedocs.io/en/latest/computation.html#integration-state) and call `mj_forward`. I expect this will be faster than `mj_copyData`. If you still want to use `mj_copyData`, perhaps for convenience, you can make it faster by reducing allocated memory. The latest version of `simulate` (not in any release, at head) reports the maximum amount of memory actually used. You reduce memory by using the `<size memory/>` directive. Look at 5004a4c8c5468891b5a8254cb867b70ebf683cbb for examples.

**Comment by ThoenigAdrian** [comment]
Hi Yuval,

thanks for looking into this and also thx for pointing out the more efficent way.

Diagnostic information:

**mujoco version 2.1.0:**

nbuffer: 5052592
nstack: 2062480

**mujoco version 2.3.0:**

nbuffer: 285568
nstack: 2663290

**Comment by saran-t** [comment]
@ThoenigAdrian I find it rather suspicious that `mj_step` is 3x faster now compared to 2.1.0. I'm not aware of anything that we've done that could've caused it to run quite _that_ much faster.

Are your numbers reliably reproducible? Would you mind running it against a few different versions in between?

**Comment by ThoenigAdrian** [comment]
Yes it's reliable reproducible.

I can understand your suspicion. I thought the same in the beginning.
But this is just because mj_copyData takes longer therefore mj_step has less time to run.

And since the time I let my application is fixed (around 20 seconds) less time is spent in mj_step

**Comment by ThoenigAdrian** [comment]
I currently don't have enough time to run it against a few different versions. But when I do in the future I'll let you know the results.

**Comment by ThoenigAdrian** [comment]
@yuvaltassa copying the state and recreating the contents of mjData works fine for me.
