### ISSUE TITLE
Could anyone please explain scale and units of measure in MuJoCo?

### ISSUE THREAD

**Issue by MotorCityCobra** [deepmind/mujoco#60]
I've looked at the docs and maybe I've missed it. When writing an XML file you start with the first object in the body, then add geoms to it and joints. Where do the specific positions come from to assemble joints correctly? I'm confused because Emo, the creator of MuJoCo has said that MuJoCo has not units of measure.  
Do meshes function as geoms on their own, or is there a problem with the way their shape is rendered that requires new shapes in their place? I ask because I notice a lot of cubes and cylinders inside of meshes in XML model files I've seen online.

**Comment by yuvaltassa** [comment]
The units of length are indeed undefined, you are free to interpret them as you like (metre, centimetre, inch etc.)

People very often add a layer of colliding primitive geoms alongside their non-colliding meshes (which are used for visualisation and inertial properties), since primitive collisions are faster to compute than mesh collisions.

**Comment by MotorCityCobra** [comment]
> The units of length are indeed undefined

For the position, `pos` in '<geom name="link1" type="mesh" mesh="leg" pos="0 0 180"/>`   
What is the `180`? What is it 180 of?
