### ISSUE TITLE
Multi threading for large scene

### ISSUE THREAD

**Issue by MyelinsheathXD** [deepmind/mujoco#627]
I want to train models in mujoco and use them in video games . 
Any plans to make  mujoco  ready for large scene simulation for real-time interactions?

**Comment by yuvaltassa** [comment]
We have no near term plans to enable multi-threading _inside_ a single large scene.

MuJoCo's threading model is designed to parallelise across scenes, rather than inside a scene, as it is made for model-based control, rather than gaming. See, for example, our recently released [MJPC](https://www.youtube.com/watch?v=Bdx7DuAMB6o) tool.
