### ISSUE TITLE
How to use anisotropic friction coefficients in some body frame?

### ISSUE THREAD

**Issue by vmanoj1996** [deepmind/mujoco#67]
Friction section in [mjcf modelling page](https://mujoco.readthedocs.io/en/latest/modeling) does not convey the direction over which anisotropic friction force is exerted.

I am trying something similar to [ice skating](https://roboti.us/forum/index.php?threads/anisotropic-skating-friction.4204/). Some experimentation reveals that it is acting along world frame's x, y axis. 

Is there a way to get around this?

**Comment by yuvaltassa** [comment]
Hi,

Anisotropic friction is tightly coupled to the specific collider used, as the collider determines the orientation of the contact frame. One usable collider for this purpose is capsule-plane, since the contact frame is always oriented along the capsule.  Below is a minimal "ice skating" example:

![ice_skate](https://user-images.githubusercontent.com/6387526/142996560-180dd634-772d-458b-9373-64a43402a2d9.gif)

```
<mujoco model="ice skate">
  <asset>
    <texture name="grid" type="2d" builtin="checker" rgb1=".1 .2 .3" rgb2=".2 .3 .4" width="512" height="512"/>
    <material name="grid" texture="grid" texrepeat="1 1" texuniform="true" reflectance=".2"/>
  </asset>

  <worldbody>
    <geom name="floor" pos="0 0 0" size="5 5 .05" type="plane" material="grid"/>
    <body name="leg" pos="0 0 .3">
      <joint type="slide" axis="1 0 0"/>
      <joint type="slide" axis="0 1 0"/>
      <joint type="slide" axis="0 0 1"/>
      <joint type="hinge" axis="0 0 1"/>
      <light pos="0 0 2"/>
      <geom name="shin" type="box" size=".03 .02 .2"/>
      <geom name="skate" type="capsule" fromto=".02 0 -.25 .1 0 -.25" size=".02"/>
    </body>
  </worldbody>

  <contact>
    <pair name="non-isotropic" geom1="floor" geom2="skate" condim="3" friction="0.1 1"/>
  </contact>
</mujoco>
```
