### ISSUE TITLE
A rendering bug

### ISSUE THREAD

**Issue by emailweixu** [deepmind/mujoco#721]
In the model, the rendering of the box is affected by the ground plane. Without the ground plane, it is correctly rendered. With the ground plane, part of the box become transparent. What I expect is that box should not become transparent.

The model and rendering code: https://colab.research.google.com/drive/1yXi683FxQxgWAf8U9eH52BqaW13roBAK

Rendered without ground plane
![image](https://user-images.githubusercontent.com/9756952/216479267-365f5073-f869-47de-86df-558ada325eb9.png)
Rendered image without ground plane
![image](https://user-images.githubusercontent.com/9756952/216479297-a78e9bf0-73fd-4996-85c7-aab5acfccdf2.png)

- Include the following context:
  - Operating system: Ubuntu 20.04.5
  - MuJoCo version: 2.3.1
  - For Python issues, what bindings are you using: mujoco

**Comment by yuvaltassa** [comment]
This is due to the far and near clipping planes that are affected by `extent` which is automatically computed unless specified by the user.

Search the documentation for "znear" "zfar" and "extent" and play with your model in the interactive viewer while moving the camera around.

Some general background in how openGL does rendering would also help (read about the frustum).

**Comment by emailweixu** [comment]
Thanks for the prompt reply. Setting znear to a smaller value does solve the problem.

> This is due to the far and near clipping planes that are affected by `extent` which is automatically computed unless specified by the user.
> 
> Search the documentation for "znear" "zfar" and "extent" and play with your model in the interactive viewer while moving the camera around.
> 
> Some general background in how openGL does rendering would also help (read about the frustum).
