### ISSUE TITLE
will there be the support for GPU executing?

### ISSUE THREAD

**Issue by im-Kitsch** [deepmind/mujoco#85]
Hi, 

it's amazing that mujoco is open-source now. I wanna to ask that if there will be GPU support in the future? It would be pretty nice and exciting. 

Thanks in advance.

**Comment by MotorCityCobra** [comment]
Using the GPU for what?  
When I open an XML in the simulate program I see the GPU is using it.  
Are you using Nvidia? Type `nvidia-smi`.
See the process.

![Screenshot 2021-12-02 170104](https://user-images.githubusercontent.com/14045554/144510288-e364be29-ced2-47f0-8e12-abd0c2ce758a.png)

**Comment by aseembits93** [comment]
I think what the OP means is that the simulations should happen on the GPU. Not sure if that's a priority for the development team.

**Comment by aditya-shirwatkar** [comment]
Yeah, it will be awesome if the devs develop something like Nvidia's Isaac Gym

**Comment by joehays** [comment]
> Yeah, it will be awesome if the devs develop something like Nvidia's Isaac Gym

Our group has seen 20+ speed up by using Isaac Gym versus Mujoco for RL training. The main reason is the GPU acceleration and an implementation that minimizes CPU-GPU communcation. By pushing "everything" to the GPU the CPU-GPU communication goes away and the total system performance jumps. This is all enabled by Isaac Gym providing tensor interfaces to PhysX (which runs on the GPU). 

If mujoco devs move mujoco to the GPU make sure you enable a tensor interface so pyTorch-based RL seemlessly communicates with the dynamics engine on the GPU and no CPU comms are needed.

**Comment by nik7273** [comment]
+1! I'd rather not switch to Isaac, but with the performance boost that Isaac promises, it's hard to say no

**Comment by nimrod-gileadi** [comment]
How are you running MuJoCo?

The MuJoCo C library is fast, but unfortunately, stepping environments through Python is indeed very slow. The way to get performance out of MuJoCo is to:

1. Run many environments in parallel, to max out your CPU cores.
2. Do as much of your run loop as possible in C/C++ rather than Python.
3. If you can evaluate your policies on CPU in the same thread as stepping the physics, run many environments independently without batching.
4. If you need to run your policy on an accelerator, make sure to batch and use a large number of environments.

Python does not let you do real parallelisation, because of the [Global Interpreter Lock](https://wiki.python.org/moin/GlobalInterpreterLock).

[envpool](https://github.com/sail-sg/envpool/tree/main/envpool) is one project offering C++ implementations of common RL environments with a batched Python API. Their [benchmark results](https://github.com/sail-sg/envpool/tree/main/envpool) show that MuJoCo performance is in the same ballpark as Isaac Gym.

 We also posted some numbers, which you should be able to reproduce with the testspeed binary we released, in our blog post: https://www.deepmind.com/blog/open-sourcing-mujoco

Regarding efficiently running neural networks on CPU, I don’t have an open source project to point you at, but that’s the direction you should go towards for small networks (e.g. MLP with layer sizes 512, 256, 128).

**Comment by sliptime** [comment]
#
