### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by RichardTicon** [deepmind/mujoco#94]
Are there any plans to speed up MuJoCo to be as fast as Raisim? This physical engine seems like 50% [faster](https://github.com/raisimTech/raisimLib/blob/95793e51ead59744d2de1b691a767759149a0445/docs/sections/Performance.rst) than MuJoCo.

**Comment by yuvaltassa** [comment]
1. RaiSim is indeed a fast simulator. However, as the developers acknowledge, their algorithms are not published and there is no way for us to know if there is some subtle speed/accuracy tradeoff without very careful experiments. 
2. It is generally quite difficult to fairly compare physics simulators. Each simulator works best in different settings and requires well-tuned models for proper comparison. Regarding fairness, we recently made an important change to our [testspeed](https://github.com/deepmind/mujoco/blob/main/sample/testspeed.cc) utility: we are now injecting noise into actuators. Because the system can no longer settle into a single fixed state where solver warm-starts can speed up the computation, speeds reported by `testspeed` are now **slower but more honest**. We generally recommend doing your own speed comparisons on the systems you care about.
3. Although MuJoCo is already quite fast, we are of course working to speed it up and indeed version 2.1.1 is [~20% faster on Linux and MacOS](https://mujoco.readthedocs.io/en/latest/changelog.html#binary-build) simply due to optimised compilation settings. However our main focus is currently getting the code ready for open-sourcing. Since MuJoCo's codebase is well organised and quite readable, we expect collaboration with external contributors to quickly drive development forward, including with respect to speed.
